name: Response Time CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  response-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: astradial/uptime-monitor@v1.41.1-astradial
        with:
          command: response-time
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
